/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimerCasualRouteImport } from './routes/timer/casual'
import { Route as TestingsFontsRouteImport } from './routes/testings/fonts'

const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const TimerCasualRoute = TimerCasualRouteImport.update({
  id: '/timer/casual',
  path: '/timer/casual',
  getParentRoute: () => rootRouteImport,
})
const TestingsFontsRoute = TestingsFontsRouteImport.update({
  id: '/testings/fonts',
  path: '/testings/fonts',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuRoute: MenuRoute,
  TestingsFontsRoute: TestingsFontsRoute,
  TimerCasualRoute: TimerCasualRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
